version: "3.9"
services:
  
  jupyter:
    build: 
     context: .
     dockerfile: Dockerfile

    volumes:
      - ../:/home/work

    environment:
      HOME: "/home/work/"
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SCECRET_ACCESS_KEY: ${AWS_SCECRET_ACCESS_KEY}


    user: 1000:1000

    restart: always
    working_dir: /home/work
    container_name: PythonPractice

    #command: poetry run jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/home/work'
    command: sleep 400000

    




