@startuml


package "common_libs" {
    package "commoon_lib1" {
    }
    package "commoon_lib2" {
    }
    
    commoon_lib1 -[hidden]right- commoon_lib2
}

package "service_lib" {
    package "service_lib1" {
    }
    package "service_lib2" {
    }
    package "service_lib3" {
    }
    
    service_lib1 -[hidden]right- service_lib2
    service_lib2 -[hidden]right- service_lib3    
}

"common_libs" --center-> "service_lib"

@enduml